repos:
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
      args:
      - --line-length=120
      language_version: python3.10
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args:
      - "--max-line-length=120"
      stages: [commit]
      exclude: __init__.py
